server:
  port: 8080
  # servlet:
  #   context-path: /api

spring:
  application:
    name: resilience4j-demo
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    serialization:
      write-dates-as-timestamps: false

resilience4j:
  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        slidingWindowType: count_based
        recordExceptions:
          - com.example.resilience4jdemo.exception.ServiceException
        ignoreExceptions:
          - java.lang.IllegalArgumentException
  retry:
    instances:
      userService:
        maxAttempts: 3
        waitDuration: 500ms
  ratelimiter:
    instances:
      processService:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0s

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,circuitbreakers,circuitbreakerevents,retries,retryevents,ratelimiters,ratelimiterevents
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: INFO
    com.example.resilience4jdemo: DEBUG
    io.github.resilience4j: INFO 